# Use custom format



# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = true

[character]
success_symbol = "[Î»](bold green) "
error_symbol = "[Î»](bold red) "

[[battery.display]]
threshold = 80
style = "bold red"

[git_status]
conflicted = "conflictedÃ—${count}(red) "
ahead = "ahead Ã—${count}"
behind = "behindÃ—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "untrackedÃ—${count} "
stashed = "stashed "
modified = "ğŸ“Ã—${count} "
staged = "stagedÃ—${count} "
renamed = "renamedÃ—${count} "
deleted = "deletedÃ—${count} "
style = "bright-white "
format = "$all_status$ahead_behind"

[golang]
symbol="go "

[python]
symbol="py "

[java]
symbol="java "
